# Generated by Django 2.2.3 on 2019-07-31 18:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='incomewarrant',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='incomewarrant',
            name='issued_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 31, 18, 49, 12, 228196, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
