# Generated by Django 2.2.3 on 2019-09-12 16:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20190809_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeinvoice',
            name='issued_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 16, 35, 8, 32949, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='incomeinvoice',
            name='received_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_income', to='inventory.Counterparty'),
        ),
        migrations.AlterField(
            model_name='incomewarrant',
            name='issued_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 16, 35, 8, 29087, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='incomewarrant',
            name='received_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_income', to='inventory.Counterparty'),
        ),
        migrations.AlterField(
            model_name='outcomeinvoice',
            name='given_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_outcome', to='inventory.Counterparty'),
        ),
        migrations.AlterField(
            model_name='outcomeinvoice',
            name='issued_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 16, 35, 8, 34730, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='outcomewarrant',
            name='given_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_outcome', to='inventory.Counterparty'),
        ),
        migrations.AlterField(
            model_name='outcomewarrant',
            name='issued_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 16, 35, 8, 31106, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='productincome',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_income', to='inventory.Product'),
        ),
        migrations.AlterField(
            model_name='productoutcome',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_outcome', to='inventory.Product'),
        ),
    ]
